g_current_version = "0.3.0"

g_release_notes = {
    ["0.1.0"] = "Initial Release. Limited to brig.",
    ["0.2.0"] = [[
- New ship added: The Bomb Ketch. While the two most famous ships of this class were not known for their martial prowess but for the ill-fated polar exploration  of HMS Eberus and HMS Terror, they have an important presence in the Age of Sail era. With the main armament being a mortar on the bow, they can deliver significant, but not accurate, damage to the enemies from afar. 

- Mortar shot: To accomodate the newcomer, I have implemented a new mortar shot feature. Rightclick the ship you want to fire upon, and select "Mortar fire". The game will roll a dice and more importante, determine the direction of the dispersion and show a line where the shot will land. Much more precise and comfortable than even in the physical game!

- Changing ammo/gun panel: The big feature of the release. When you select a ship, you have now a list of weapons on each position on the top right of the screen. You can fire from there if you feel clicking from the ship is too finicky, but you can also click on the ammunition icon and change to whatever ammo you prefer, with the corresponding custom icons. Furthermore, if you fire on a position, the icon will be greyed out until you roll for wind and the start of the next turn.

- Terrain: While most battles happen at rather open sea, it's not that uncommon, especially for the smaller ships, to fight near coasts, island or tricky terrain. The terrain uses a custom triplanar shader, which means that you can put two elements together and the texture will be continuous. For the moment, there's a cliff, a beach (that can be submerged to make smaller islands or sandbanks) and several rocks that with some placement skills can be made to create many types of rocky features. Additionally, there's two fog/squall pieces for those ambushes at sea. Finally, since it can be very tedious to lock everything manually, I have created a fix terrain button that it does exactly that.

- Changing board size: You can now click on the bottom left to select if you want a 6x4' standard game, 3x4' small one or 8x6 for the biggest battles.

- Select crew experience level: Fairly straightforward, when you select the ship to create, you can choose if you want to be Veterans, Regular or Inexperienced.

- Fixed a bug where the bow sail of the Brig was not getting furled on Battle Sails.
    ]],
    ["0.2.1"] = [[
- Undo feature: Each ship stores it's position after moving and turning, and with a button next to the Move/Turn you can Undo to move it back.

- Better summary: On the top left all ships are listed. But now if you have a ship below break value, they will be on yellow. And if they surrender or capsize, they will be red.

- Fixed an error where the sails were not visible in certain resolutions.
    ]],
    ["0.3.0"] = [[
- New ship added: The frigate. The common frigate, a 5th rate usually equipped with 32 guns. They are fast, well equipped for most situations like piracy, and they don't have as much problems with shallower coasts like the USA.

- New ship added: The third rate. The 74-cannon beast is essentially the workhorse of naval battles in this period, with a good capability for manouvres while still having impressive firepower.

- Initial broadsides: The first time a ship shoots its broadsides, it has additional cannons depending on size. This is now automated, and the mod takes into account ranges.

- Ship upgrades: You can now add upgrades for the ships! This gives a lot of options for customization.

- Added a mast hit button for that critical result. When clicked, it will remvoe one of the masts of the ship, visually representing the hit.

- More terrain: A dock has been added.

- Better wind: When you click on the wind on each turn, in addition to the chat log, the order of the ships is also shown on a list below the button, which is useful in bigger battles. Additionally, there are now buttons to set the wind to specific directions.

- Ammo: Changing ammo also is reflected on the range indicators depending on which type.

- Fix: The mortar shoots 360º now, which was incorrectly only shooting in the position mounted.
    ]]
}