ship_types = {
    -- Each of these types must refer to a type in data_ships!
    shiptype_brig = 0,
    shiptype_bomb_ketch = 1,
    shiptype_frigate = 2,
    shiptype_3rd = 3,
    shiptype_frigate_6th = 4,
    shiptype_small_3rd = 5,
    shiptype_small_merchant = 6,

    fortification_gun_emplacement = 100,
    fortification_mortar_emplacement = 101,
    fortification_martello = 102,

    shiptype_bucentaure = 200,
    shiptype_bellerophon = 201,
    shiptype_la_princesa = 202,
    shiptype_essex = 202,
}

data_ships = {}

data_ships.shiptype_brig = {
    ship_points = 20,
    break_value = 7,
    points = 80,
    turn_angle = turn_angles.Red,
    size = "S",
    knots = 5,
    cannons = {
        Bow = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 2,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Starboard = {
            heavy = 2,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 0,
        Port = 1,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1776075290156934315/4E4C0771788E84C2DF6F22DA1AA4C41DCEC5A302/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard4 = true,
                yard5 = true,
                yard6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mainmast = true,
                yard1 = true,
                yard2 = true,
                yard3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
                cat = true
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=1.1153, y=0.325, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.29, y=0.129, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=0.848, y=0.331, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-0.409, y=0.292, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=1.858, y=0.681, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard1 = {
            scale = {x=1, y=1, z=1},
            pos_offset = {x=-0.32, y=1.061, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard2 = {
            scale = {x=1, y=1, z=0.76763},
            pos_offset = {x=-0.29, y=1.81, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard3 = {
            scale = {x=0.8, y=0.6, z=0.5},
            pos_offset = {x=-0.285, y=2.372, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard4 = {
            scale = {x=1, y=1, z=0.846},
            pos_offset = {x=0.87, y=1.122, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard5 = {
            scale = {x=1, y=0.8, z=0.71},
            pos_offset = {x=0.92, y=1.826, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard6 = {
            scale = {x=0.72, y=0.56, z=0.45},
            pos_offset = {x=0.92, y=2.3258, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=1.653,y=0.678,z=0},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.189,y=0.9,z=0},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=1.889,y=0.663,z=0},
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=0.92,y=1.119,z=0},
            references_sail = "main_l",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=0.949,y=1.826,z=0},
            references_sail = "gallant_l",
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            scale = {x=0.95, y = 0.95, z=0.95},
            pos_offset = {x=0.956,y=2.32,z=0},
            references_sail = "top_s",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.3,y=1.056,z=0},
            references_sail = "main_xl",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.29,y=1.81,z=0},
            references_sail = "gallant_xl",
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.285,y=2.370,z=0},
            references_sail = "top_s",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-0.443,y=1.033,z=0},
            references_sail = "cat",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-1.07,y=1.27,z=-0.1},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            pos_offset = {x=-0.288,y=2.48,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_bomb_ketch = {
    ship_points = 20,
    break_value = 7,
    points = 80,
    turn_angle = turn_angles.Red,
    size = "S",
    knots = 5,
    cannons = {
        Bow = {
            heavy = 0,
            light = 0,
            mortar = 1,
            carronade = 0
        },
        Port = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Starboard = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 0,
        Port = 0,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1772698858473874252/FD1BBAC1325D6EAC7990736EDD9274BC29BEDC36/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true,
                gaff = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=0.9673001, y=0.403, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=0.62, y=0.163, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=-0.388, y=0.147, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-0.456, y=0.292, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=1.71, y=0.755, z=0},
            scale = {x=1, y=1, z=1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1, y=1, z=1},
            pos_offset = {x=0.620, y=1.136, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1, y=1, z=0.76763},
            pos_offset = {x=0.623, y=1.878, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=0.8, y=0.6, z=0.5},
            pos_offset = {x=0.629, y=2.328, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1, y=1, z=0.846},
            pos_offset = {x=-0.366, y=1.009, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1, y=0.8, z=0.71},
            pos_offset = {x=-0.335, y=1.662, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=0.72, y=0.56, z=0.45},
            pos_offset = {x=-0.312, y=2.177, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=1.46,y=0.758,z=0},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=1.956,y=0.957,z=0},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=1.699,y=0.745,z=0},
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=-0.356,y=1.009,z=0},
            references_sail = "main_l",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=-0.335,y=1.652,z=0},
            references_sail = "gallant_l",
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            scale = {x=0.95, y = 0.95, z=0.95},
            pos_offset = {x=-0.312,y=2.167,z=0},
            references_sail = "top_s",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=0.636,y=1.13,z=0},
            references_sail = "main_xl",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=0.647,y=1.878,z=0},
            references_sail = "gallant_xl",
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=0.651,y=2.322,z=0},
            references_sail = "top_s",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-0.501,y=1.033,z=0},
            references_sail = "cat",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-1.309,y=1.27,z=-0.1},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            pos_offset = {x=0.619,y=2.493,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_small_merchant = {
    ship_points = 28,
    break_value = 10,
    points = 40,
    turn_angle = turn_angles.Yellow,
    size = "M",
    knots = 3,
    cannons = {
        Bow = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 1,
            light = 1,
            mortar = 0,
            carronade = 0
        },
        Starboard = {
            heavy = 1,
            light = 1,
            mortar = 0,
            carronade = 0
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 1,
        Port = 0,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1773826716846552084/DAD75E83092CEBF2134B05085EFA9B2BF66D767F/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true,
                jib3 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=1.457, y=0.458, z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.22, y=0.3089999, z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=0.9930001, y=0.441, z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.355, y=0.499, z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.417, y=0.53, z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=2.462, y=0.944, z=0},
            scale = {x=1.2, y=1.2, z=1-2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.2, y=1.2, z=1.2},
            pos_offset = {x=-0.146, y=1.47, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.2, y=1.2, z=0.84},
            pos_offset = {x=-0.184, y=2.491, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=0.96, y=0.72, z=0.6},
            pos_offset = {x=-0.179, y=3.037, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=1.093, y=1.477, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=1.087, y=2.293, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=1.11, y=2.865, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=-1.276, y=1.507, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=-1.27, y=2.379, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=-1.233, y=2.952, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.599,y=1.125,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.248,y=0.993,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        jib3 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=1.919,y=0.844,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        bow = {
            pos_offset = {x=2.462,y=0.944,z=0},
            scale = 1.2,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=1.093,y=1.477,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=1.087,y=2.293,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=1.11,y=2.865,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.146,y=1.47,z=0},
            references_sail = "main_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.184,y=2.491,z=0},
            references_sail = "gallant_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.179,y=3.037,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.276,y=1.507,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.27,y=2.379,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.233,y=2.952,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.474,y=1.422,z=0},
            references_sail = "cat",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.461,y=1.373,z=-0.1},
            scale = {x=1.2,y=1.2,z=1.2},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            pos_offset = {x=-0.212,y=3.149,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_frigate = {
    ship_points = 36,
    break_value = 12,
    points = 150,
    turn_angle = turn_angles.Red,
    size = "M",
    knots = 5,
    cannons = {
        Bow = {
            heavy = 0,
            light = 1,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 2,
            light = 1,
            mortar = 0,
            carronade = 1
        },
        Starboard = {
            heavy = 2,
            light = 1,
            mortar = 0,
            carronade = 1
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 2,
        Port = 1,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951292184167950/4BB8EA9CBCD796DFD1CD1C384D92CAD622D3668F/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=1.534, y=0.416, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.3405, y=0.3446, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=1.082, y=0.298, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.54, y=0.38, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.598, y=0.405, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=2.434, y=0.825, z=0},
            scale = {x=1.2, y=1.2, z=1-2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.2, y=1.2, z=1.2},
            pos_offset = {x=-0.306, y=1.463, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.2, y=1.2, z=0.84},
            pos_offset = {x=-0.319, y=2.353, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=0.96, y=0.72, z=0.6},
            pos_offset = {x=-0.325, y=2.822, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=1.146, y=1.234, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=1.175, y=2.026, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=1.182, y=2.504, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=-1.482, y=1.32, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=-1.459, y=2.067, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=-1.445, y=2.582, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.156,y=0.83,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.658,y=1.042,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=2.434,y=0.825,z=0},
            scale = 1.2,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=1.146,y=1.234,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=1.175,y=2.026,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=1.182,y=2.504,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.306,y=1.463,z=0},
            references_sail = "main_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.319,y=2.353,z=0},
            references_sail = "gallant_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.325,y=2.822,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.482,y=1.32,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.459,y=2.067,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.445,y=2.582,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.617,y=1.224,z=0},
            references_sail = "cat",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.551,y=1.238,z=-0.1},
            scale = {x=1.2,y=1.2,z=1.2},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            pos_offset = {x=-0.35,y=2.958,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_frigate_6th = {
    ship_points = 28,
    break_value = 10,
    points = 120,
    turn_angle = turn_angles.Red,
    size = "M",
    knots = 5,
    cannons = {
        Bow = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 1,
            light = 1,
            mortar = 0,
            carronade = 1
        },
        Starboard = {
            heavy = 1,
            light = 1,
            mortar = 0,
            carronade = 1
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 2,
        Port = 1,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951292184167950/4BB8EA9CBCD796DFD1CD1C384D92CAD622D3668F/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=1.534, y=0.416, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.3405, y=0.3446, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=1.082, y=0.298, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.54, y=0.38, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.598, y=0.405, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=2.434, y=0.825, z=0},
            scale = {x=1.2, y=1.2, z=1-2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.2, y=1.2, z=1.2},
            pos_offset = {x=-0.306, y=1.463, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.2, y=1.2, z=0.84},
            pos_offset = {x=-0.319, y=2.353, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=0.96, y=0.72, z=0.6},
            pos_offset = {x=-0.325, y=2.822, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=1.146, y=1.234, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=1.175, y=2.026, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=1.182, y=2.504, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=-1.482, y=1.32, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=-1.459, y=2.067, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=-1.445, y=2.582, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.156,y=0.83,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.658,y=1.042,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=2.434,y=0.825,z=0},
            scale = 1.2,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=1.146,y=1.234,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=1.175,y=2.026,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=1.182,y=2.504,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.306,y=1.463,z=0},
            references_sail = "main_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.319,y=2.353,z=0},
            references_sail = "gallant_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.325,y=2.822,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.482,y=1.32,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.459,y=2.067,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.445,y=2.582,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.617,y=1.224,z=0},
            references_sail = "cat",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.551,y=1.238,z=-0.1},
            scale = {x=1.2,y=1.2,z=1.2},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            pos_offset = {x=-0.35,y=2.958,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_3rd = {
    ship_points = 74,
    break_value = 25,
    points = 280,
    turn_angle = turn_angles.Red,
    size = "L",
    knots = 4,
    cannons = {
        Bow = {
            heavy = 1,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 3,
            light = 2,
            mortar = 0,
            carronade = 2
        },
        Starboard = {
            heavy = 3,
            light = 2,
            mortar = 0,
            carronade = 2
        },
        Stern = {
            heavy = 0,
            light = 1,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 2,
        Port = 1,
        Bow = 0,
        Stern = 3
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951381941096725/22EA9ECC452B3552D6C6CFF9BAEF65493F2A7E02/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=2.255, y=0.522, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.087, y=0.663, z=0},
            scale = {x=1.3, y=1.3, z=1.3},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=1.944, y=0.5869999, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.391, y=0.793, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.453, y=0.824, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=3.4161, y=1.1008, z=0},
            scale = {x=1.3, y=1.3, z=1.3},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.4, y=1.4, z=1.4},
            pos_offset = {x=-0.023, y=1.986, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.4, y=1.4, z=0.98},
            pos_offset = {x=-0.053, y=3.082, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=1.11, y=0.84, z=0.7},
            pos_offset = {x=-0.063, y=3.669, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.4, y=1.3, z=1.187784},
            pos_offset = {x=2.044, y=1.762, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.4, y=1.1232, z=1.0179},
            pos_offset = {x=2.022, y=2.772, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=1.099332, y=0.8503056, z=0.6951744},
            pos_offset = {x=2.061, y=3.394, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.4, y=1.4, z=1.187784},
            pos_offset = {x=-1.312, y=1.96, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.4, y=1.12, z=1},
            pos_offset = {x=-1.306, y=2.956, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=1, y=0.7862, z=0.6318},
            pos_offset = {x=-1.269, y=3.629, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.89,y=0.949,z=0},
            scale = 1.3,
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=3.534,y=1.257,z=0},
            scale = 1.3,
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=3.4161,y=1.1008,z=0},
            scale = 1.3,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=2.044,y=1.762,z=0},
            references_sail = "main_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=2.022,y=2.772,z=0},
            references_sail = "gallant_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=2.061,y=3.394,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.023,y=1.986,z=0},
            references_sail = "main_xl",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.053,y=3.082,z=0},
            references_sail = "gallant_xl",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.063,y=3.669,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.312,y=1.96,z=0},
            references_sail = "main_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.306,y=2.956,z=0},
            references_sail = "gallant_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.269,y=3.629,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.505,y=1.861,z=0},
            references_sail = "cat",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.724,y=1.965,z=-0.1},
            scale = {x=1.4, y=1.4, z=1.4},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            scale = {x=1.3, y=1.3, z=1.3},
            pos_offset = {x=-0.089,y=3.826,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_small_3rd = {
    ship_points = 64,
    break_value = 22,
    points = 250,
    turn_angle = turn_angles.Red,
    size = "L",
    knots = 4,
    cannons = {
        Bow = {
            heavy = 1,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 3,
            light = 2,
            mortar = 0,
            carronade = 1
        },
        Starboard = {
            heavy = 3,
            light = 2,
            mortar = 0,
            carronade = 1
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 2,
        Port = 1,
        Bow = 0,
        Stern = 3
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951381941096725/22EA9ECC452B3552D6C6CFF9BAEF65493F2A7E02/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=2.255, y=0.522, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.087, y=0.663, z=0},
            scale = {x=1.3, y=1.3, z=1.3},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=1.944, y=0.5869999, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.391, y=0.793, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.453, y=0.824, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=3.4161, y=1.1008, z=0},
            scale = {x=1.3, y=1.3, z=1.3},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.4, y=1.4, z=1.4},
            pos_offset = {x=-0.023, y=1.986, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.4, y=1.4, z=0.98},
            pos_offset = {x=-0.053, y=3.082, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=1.11, y=0.84, z=0.7},
            pos_offset = {x=-0.063, y=3.669, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.4, y=1.3, z=1.187784},
            pos_offset = {x=2.044, y=1.762, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.4, y=1.1232, z=1.0179},
            pos_offset = {x=2.022, y=2.772, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=1.099332, y=0.8503056, z=0.6951744},
            pos_offset = {x=2.061, y=3.394, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.4, y=1.4, z=1.187784},
            pos_offset = {x=-1.312, y=1.96, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.4, y=1.12, z=1},
            pos_offset = {x=-1.306, y=2.956, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=1, y=0.7862, z=0.6318},
            pos_offset = {x=-1.269, y=3.629, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.89,y=0.949,z=0},
            scale = 1.3,
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=3.534,y=1.257,z=0},
            scale = 1.3,
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=3.4161,y=1.1008,z=0},
            scale = 1.3,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=2.044,y=1.762,z=0},
            references_sail = "main_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=2.022,y=2.772,z=0},
            references_sail = "gallant_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=2.061,y=3.394,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.023,y=1.986,z=0},
            references_sail = "main_xl",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.053,y=3.082,z=0},
            references_sail = "gallant_xl",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.063,y=3.669,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.312,y=1.96,z=0},
            references_sail = "main_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.306,y=2.956,z=0},
            references_sail = "gallant_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.269,y=3.629,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.505,y=1.861,z=0},
            references_sail = "cat",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.724,y=1.965,z=-0.1},
            scale = {x=1.4, y=1.4, z=1.4},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            scale = {x=1.3, y=1.3, z=1.3},
            pos_offset = {x=-0.089,y=3.826,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.fortification_gun_emplacement = {
    is_fortification = true,
    ship_points = 10,
    break_value = 4,
    points = 40,
    turn_angle = turn_angles.Red,
    forced_name = "Shore Gun Emplacement",
    size = "M",
    knots = 0,
    cannons = {
        Bow = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 1,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Starboard = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 0,
        Port = 0,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951893767609606/65F8979AD5C62CDBF4BFA301FDDCBF2314C250DB/"
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=0, z=0},
            pos_offset = {x=-0.049,y=1.12,z=0.227},
            scale = {x=0.7, y=0.7, z=0.7},
            references_nation = "flag_ensign"
        }
    }
}

data_ships.fortification_mortar_emplacement = {
    is_fortification = true,
    ship_points = 10,
    break_value = 4,
    points = 50,
    turn_angle = turn_angles.Red,
    forced_name = "Shore Mortar Emplacement",
    size = "M",
    knots = 0,
    cannons = {
        Bow = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 0,
            light = 0,
            mortar = 1,
            carronade = 0
        },
        Starboard = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 0,
        Port = 0,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951893767609942/B479171239D1018C0209A693734EE700C9B75ABD/"
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=0, z=0},
            pos_offset = {x=-0.049,y=1.12,z=0.227},
            scale = {x=0.7, y=0.7, z=0.7},
            references_nation = "flag_ensign"
        }
    }
}

data_ships.fortification_martello = {
    is_fortification = true,
    ship_points = 150,
    break_value = 50,
    points = 250,
    turn_angle = turn_angles.Red,
    forced_name = "Martello Tower",
    size = "L",
    knots = 0,
    cannons = {
        Bow = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 3,
            light = 3,
            mortar = 0,
            carronade = 0
        },
        Starboard = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 0,
        Port = 0,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774952098007522273/E0204386DB8A418FDF93C5B415AA0D1A10D8B2E5/"
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=0, z=0},
            pos_offset = {x=-0.01,y=2.604,z=0},
            scale = {x=0.8, y=0.8, z=0.8},
            references_nation = "flag_ensign"
        }
    }
}

data_ships.shiptype_bucentaure = {
    ship_points = 84,
    break_value = 28,
    points = 370,
    turn_angle = turn_angles.Red,
    forced_name = "Bucentaure",
    size = "L",
    knots = 4,
    cannons = {
        Bow = {
            heavy = 1,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 3,
            light = 3,
            mortar = 0,
            carronade = 2
        },
        Starboard = {
            heavy = 3,
            light = 3,
            mortar = 0,
            carronade = 2
        },
        Stern = {
            heavy = 0,
            light = 1,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 2,
        Port = 1,
        Bow = 0,
        Stern = 3
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951381941096725/22EA9ECC452B3552D6C6CFF9BAEF65493F2A7E02/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=2.255, y=0.522, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.087, y=0.663, z=0},
            scale = {x=1.3, y=1.3, z=1.3},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=1.944, y=0.5869999, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.391, y=0.793, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.453, y=0.824, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=3.4161, y=1.1008, z=0},
            scale = {x=1.3, y=1.3, z=1.3},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.4, y=1.4, z=1.4},
            pos_offset = {x=-0.023, y=1.986, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.4, y=1.4, z=0.98},
            pos_offset = {x=-0.053, y=3.082, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=1.11, y=0.84, z=0.7},
            pos_offset = {x=-0.063, y=3.669, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.4, y=1.3, z=1.187784},
            pos_offset = {x=2.044, y=1.762, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.4, y=1.1232, z=1.0179},
            pos_offset = {x=2.022, y=2.772, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=1.099332, y=0.8503056, z=0.6951744},
            pos_offset = {x=2.061, y=3.394, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.4, y=1.4, z=1.187784},
            pos_offset = {x=-1.312, y=1.96, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.4, y=1.12, z=1},
            pos_offset = {x=-1.306, y=2.956, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=1, y=0.7862, z=0.6318},
            pos_offset = {x=-1.269, y=3.629, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.89,y=0.949,z=0},
            scale = 1.3,
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=3.534,y=1.257,z=0},
            scale = 1.3,
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=3.4161,y=1.1008,z=0},
            scale = 1.3,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=2.044,y=1.762,z=0},
            references_sail = "main_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=2.022,y=2.772,z=0},
            references_sail = "gallant_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=2.061,y=3.394,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.023,y=1.986,z=0},
            references_sail = "main_xl",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.053,y=3.082,z=0},
            references_sail = "gallant_xl",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.063,y=3.669,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.312,y=1.96,z=0},
            references_sail = "main_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.306,y=2.956,z=0},
            references_sail = "gallant_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.269,y=3.629,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.505,y=1.861,z=0},
            references_sail = "cat",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.724,y=1.965,z=-0.1},
            scale = {x=1.4, y=1.4, z=1.4},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            scale = {x=1.3, y=1.3, z=1.3},
            pos_offset = {x=-0.089,y=3.826,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_bellerophon = {
    ship_points = 84,
    break_value = 28,
    points = 360,
    turn_angle = turn_angles.Red,
    forced_name = "HMS Bellerophon",
    size = "L",
    knots = 4,
    cannons = {
        Bow = {
            heavy = 1,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 3,
            light = 2,
            mortar = 0,
            carronade = 2
        },
        Starboard = {
            heavy = 3,
            light = 2,
            mortar = 0,
            carronade = 2
        },
        Stern = {
            heavy = 0,
            light = 1,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 2,
        Port = 1,
        Bow = 0,
        Stern = 3
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951381941096725/22EA9ECC452B3552D6C6CFF9BAEF65493F2A7E02/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=2.255, y=0.522, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.087, y=0.663, z=0},
            scale = {x=1.3, y=1.3, z=1.3},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=1.944, y=0.5869999, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.391, y=0.793, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.453, y=0.824, z=0},
            scale = {x=1.4, y=1.4, z=1.4},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=3.4161, y=1.1008, z=0},
            scale = {x=1.3, y=1.3, z=1.3},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.4, y=1.4, z=1.4},
            pos_offset = {x=-0.023, y=1.986, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.4, y=1.4, z=0.98},
            pos_offset = {x=-0.053, y=3.082, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=1.11, y=0.84, z=0.7},
            pos_offset = {x=-0.063, y=3.669, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.4, y=1.3, z=1.187784},
            pos_offset = {x=2.044, y=1.762, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.4, y=1.1232, z=1.0179},
            pos_offset = {x=2.022, y=2.772, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=1.099332, y=0.8503056, z=0.6951744},
            pos_offset = {x=2.061, y=3.394, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.4, y=1.4, z=1.187784},
            pos_offset = {x=-1.312, y=1.96, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.4, y=1.12, z=1},
            pos_offset = {x=-1.306, y=2.956, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=1, y=0.7862, z=0.6318},
            pos_offset = {x=-1.269, y=3.629, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.89,y=0.949,z=0},
            scale = 1.3,
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=3.534,y=1.257,z=0},
            scale = 1.3,
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=3.4161,y=1.1008,z=0},
            scale = 1.3,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=2.044,y=1.762,z=0},
            references_sail = "main_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=2.022,y=2.772,z=0},
            references_sail = "gallant_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=2.061,y=3.394,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.023,y=1.986,z=0},
            references_sail = "main_xl",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.053,y=3.082,z=0},
            references_sail = "gallant_xl",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.063,y=3.669,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.312,y=1.96,z=0},
            references_sail = "main_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.306,y=2.956,z=0},
            references_sail = "gallant_l",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.269,y=3.629,z=0},
            references_sail = "top_s",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.505,y=1.861,z=0},
            references_sail = "cat",
            scale = 1.4,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.724,y=1.965,z=-0.1},
            scale = {x=1.4, y=1.4, z=1.4},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            scale = {x=1.3, y=1.3, z=1.3},
            pos_offset = {x=-0.089,y=3.826,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_la_princesa = {
    ship_points = 34,
    break_value = 12,
    points = 150,
    turn_angle = turn_angles.Red,
    forced_name = "La Princesa",
    size = "M",
    knots = 5,
    cannons = {
        Bow = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 1,
            light = 1,
            mortar = 0,
            carronade = 1
        },
        Starboard = {
            heavy = 1,
            light = 1,
            mortar = 0,
            carronade = 1
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 2,
        Port = 1,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951292184167950/4BB8EA9CBCD796DFD1CD1C384D92CAD622D3668F/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=1.534, y=0.416, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.3405, y=0.3446, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=1.082, y=0.298, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.54, y=0.38, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.598, y=0.405, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=2.434, y=0.825, z=0},
            scale = {x=1.2, y=1.2, z=1-2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.2, y=1.2, z=1.2},
            pos_offset = {x=-0.306, y=1.463, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.2, y=1.2, z=0.84},
            pos_offset = {x=-0.319, y=2.353, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=0.96, y=0.72, z=0.6},
            pos_offset = {x=-0.325, y=2.822, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=1.146, y=1.234, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=1.175, y=2.026, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=1.182, y=2.504, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=-1.482, y=1.32, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=-1.459, y=2.067, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=-1.445, y=2.582, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.156,y=0.83,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.658,y=1.042,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=2.434,y=0.825,z=0},
            scale = 1.2,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=1.146,y=1.234,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=1.175,y=2.026,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=1.182,y=2.504,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.306,y=1.463,z=0},
            references_sail = "main_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.319,y=2.353,z=0},
            references_sail = "gallant_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.325,y=2.822,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.482,y=1.32,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.459,y=2.067,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.445,y=2.582,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.617,y=1.224,z=0},
            references_sail = "cat",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.551,y=1.238,z=-0.1},
            scale = {x=1.2,y=1.2,z=1.2},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            pos_offset = {x=-0.35,y=2.958,z=0},
            references_nation = "flag_pendon"
        }
    }
}

data_ships.shiptype_essex = {
    ship_points = 36,
    break_value = 12,
    points = 150,
    turn_angle = turn_angles.Red,
    forced_name = "USS Essex",
    size = "M",
    knots = 5,
    cannons = {
        Bow = {
            heavy = 0,
            light = 1,
            mortar = 0,
            carronade = 0
        },
        Port = {
            heavy = 2,
            light = 1,
            mortar = 0,
            carronade = 1
        },
        Starboard = {
            heavy = 2,
            light = 1,
            mortar = 0,
            carronade = 1
        },
        Stern = {
            heavy = 0,
            light = 0,
            mortar = 0,
            carronade = 0
        }
    },
    firing_effects = {
        Starboard = 2,
        Port = 1,
        Bow = 0,
        Stern = 0
    },
    hull = {
        customasset = "http://cloud-3.steamusercontent.com/ugc/1774951292184167950/4BB8EA9CBCD796DFD1CD1C384D92CAD622D3668F/"
    },
    broken_masts = {
        mast1 = {
            masts = {
                foremast = true,
                yard_fore_4 = true,
                yard_fore_5 = true,
                yard_fore_6 = true
            },
            sails = {
                mainfore = true,
                gallantfore = true,
                topfore = true,
                jib1 = true,
                jib2 = true
            },
            flags = {
                
            }
        },
        mast2 = {
            masts = {
                mizzenmast = true,
                yard_mizzen_7 = true,
                yard_mizzen_8 = true,
                yard_mizzen_9 = true,
                gaff = true
            },
            sails = {
                mainmizzen = true,
                gallantmizzen = true,
                topmizzen = true,
                cat = true
            },
            flags = {
                
            }
        },
        mast3 = {
            masts = {
                mainmast = true,
                yard_main_1 = true,
                yard_main_2 = true,
                yard_main_3 = true,
                gaff = true
            },
            sails = {
                mainmain = true,
                gallantmain = true,
                topmain = true,
                bow = true,
            },
            flags = {
                pendon = true
            }
        }
    },
    masts = {
        bow = {
            pos_offset = {x=1.534, y=0.416, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991356/F1A4BF2D97A108DDD1CD2127355F0B45E7D88EF9/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mainmast = {
            pos_offset = {x=-0.3405, y=0.3446, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991616/C1B4CDFE33ED8B4F6B64FFCC83EE3F84F9077ECD/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        foremast = {
            pos_offset = {x=1.082, y=0.298, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        mizzenmast = {
            pos_offset = {x=-1.54, y=0.38, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991536/A547F4C4B0207429D699DCD5526C69BFCC261D2F/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        gaff = {
            pos_offset = {x=-1.598, y=0.405, z=0},
            scale = {x=1.1, y=1.1, z=1.1},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991434/566A80FB0EAC2FF9B33F32CB8BF1C7F19E4B4C53/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        bow_spit = {
            pos_offset = {x=2.434, y=0.825, z=0},
            scale = {x=1.2, y=1.2, z=1-2},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991256/2AD4641D2D0C1E54EF824C070D18141CC5C003DE/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_1 = {
            scale = {x=1.2, y=1.2, z=1.2},
            pos_offset = {x=-0.306, y=1.463, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_2 = {
            scale = {x=1.2, y=1.2, z=0.84},
            pos_offset = {x=-0.319, y=2.353, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_main_3 = {
            scale = {x=0.96, y=0.72, z=0.6},
            pos_offset = {x=-0.325, y=2.822, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_4 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=1.146, y=1.234, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_5 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=1.175, y=2.026, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_fore_6 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=1.182, y=2.504, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_7 = {
            scale = {x=1.2, y=1.2, z=1.0152},
            pos_offset = {x=-1.482, y=1.32, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_8 = {
            scale = {x=1.2, y=0.96, z=0.86},
            pos_offset = {x=-1.459, y=2.067, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        },
        yard_mizzen_9 = {
            scale = {x=0.86, y=0.672, z=0.54},
            pos_offset = {x=-1.445, y=2.582, z=0},
            rotation = 0,
            mesh = "http://cloud-3.steamusercontent.com/ugc/1776075791924991697/64F75CDF2B84DEEB697DA8AAB82D4FA500244EFF/",
            tex = "http://cloud-3.steamusercontent.com/ugc/1776075791924257666/65995D4773D0524EBC307C08A98F653E29E034D1/"
        }
    },
    sails = {
        jib1 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.156,y=0.83,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        jib2 = {
            rotation_vector = {x=0, y=0, z=20},
            pos_offset = {x=2.658,y=1.042,z=0},
            scale = {x=1.2, y=1.2, z=1.2},
            references_sail = "jib",
            furled_on = {
                sails_setups.Anchored
            }
        },
        bow = {
            pos_offset = {x=2.434,y=0.825,z=0},
            scale = 1.2,
            references_sail = "bow",
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        mainfore = {
            pos_offset = {x=1.146,y=1.234,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantfore = {
            pos_offset = {x=1.175,y=2.026,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topfore = {
            pos_offset = {x=1.182,y=2.504,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmain = {
            pos_offset = {x=-0.306,y=1.463,z=0},
            references_sail = "main_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmain = {
            pos_offset = {x=-0.319,y=2.353,z=0},
            references_sail = "gallant_xl",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmain = {
            pos_offset = {x=-0.325,y=2.822,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        mainmizzen = {
            pos_offset = {x=-1.482,y=1.32,z=0},
            references_sail = "main_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails,
                sails_setups.Battle_Sails
            }
        },
        gallantmizzen = {
            pos_offset = {x=-1.459,y=2.067,z=0},
            references_sail = "gallant_l",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored
            }
        },
        topmizzen = {
            pos_offset = {x=-1.445,y=2.582,z=0},
            references_sail = "top_s",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        },
        cat = {
            pos_offset = {x=-1.617,y=1.224,z=0},
            references_sail = "cat",
            scale = 1.2,
            furled_on = {
                sails_setups.Anchored,
                sails_setups.Light_Sails
            }
        }
    },
    flags = {
        ensign = {
            rotation_vector = {x=0, y=200, z=10},
            pos_offset = {x=-2.551,y=1.238,z=-0.1},
            scale = {x=1.2,y=1.2,z=1.2},
            references_nation = "flag_ensign"
        },
        pendon = {
            rotation = 180,
            pos_offset = {x=-0.35,y=2.958,z=0},
            references_nation = "flag_pendon"
        }
    }
}